In [1]:
import pandas as pd, numpy as np

## How to get the array's out of numpy:

In [5]:
first_array = np.array([3,43,123])

* Please get the array with 7 elements in it:

## Get the matrix out of the array:

In [7]:
array_matrix = np.array([[2,34,5], [6,54,3]])

### Now checking the dimension(numbers of rows and columns) of the matrix.

In [9]:
array_matrix.shape

(2, 3)

* Please create a matrix with 4 rows and 5 columns and later on please do check it with some method

## Iterating over a list: use the for loop and print the results

In [ ]:
list1 = [34,5,678,6,5,4]

## Getting an extra element added with each list: In our case please add 2 to each elemeent

## Likewise in order to add any number to the numpy array we need to do the vectorization:

In [11]:
array_case = np.array([34,5,678,6,5,4])

In [12]:
array_case + 2

array([ 36,   7, 680,   8,   7,   6])

* Please create any random array and add elements to it in the vectorizatin form:

## Checking the nested looping: getting one condition in another condition. In the below case we are getting all those elments from the list that are even

In [15]:
list1 = [34,5,678,6,5,3]

In [16]:
for i in list1:
    if i % 2 == 0:
        print(i)

34
678
6


* Please get the odd numbers from the below list?
* list1 = [34,5,678,6,5,3]

## Satisfing the condition from the numpy array: firstly in the onde dimension. Get those elements that are greater than 15

In [18]:
num_arr = np.array([34,32,5,4,14,99,145])

In [19]:
num_arr > 15

array([ True,  True, False, False, False,  True,  True])

## Now we do not want booleans, but we want actual values:

In [20]:
num_arr[num_arr > 15]

array([ 34,  32,  99, 145])

* Please go through the above code and get the values that are less than 15:

## Getting the dataset for the two dimensional arrays:

In [24]:
two_dim = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [25]:
two_dim

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
two_dim[two_dim > 5]

array([6, 7, 8, 9])

* Likewise please get all the values that are less than 5.

## slicing over the to dimensions:

In [27]:
two_dim[0:2,1]

array([2, 5])

* Please help me getting 8 and 9: