## Topics to cover in the notebook:
* Generate random numbers for various distributions including integer and floats.

In [16]:
import random
## random() is the most basic function of the random module.

## Generating random integers:
* A randint(a,b) works only for integers.
* The randint(a,b) function accepts two parameters, and both are required.

In [17]:
from random import randint

In [18]:
randint(2,5)

5

## If we want some random element from the list:

In [44]:
city_list = ['New Delhi', 'Punjab', 'Karnataka', 'A.P', 'Goa']
print("Select random element from list - ", random.choice(city_list))

Select random element from list -  A.P


## Generating Multiple elements from a list:

In [48]:
list1 = [2,5,8,9,12]
print ("random.sample() ",random.sample(list1,3))

random.sample()  [5, 9, 12]


## Getting elements from a list, just the shuffling of the elements will be done:

In [49]:
list1 = [2,5,8,9,12]
random.shuffle(list1)
print ("Printing shuffled list ", list1)

Printing shuffled list  [9, 2, 8, 5, 12]


## Python Numpy module:
* Whenever you want to generate an array of random numbers you need to use numpy.random.
* numpy has the numpy.random package which has multiple functions to generate the random n-dimensional array for various distributions.

In [50]:
import numpy as np

In [51]:
np.random.rand()

0.5525249174558206

## Generate a random n-dimensional array of float numbers

* Use numpy.random.rand() to generate an n-dimensional array of random float numbers in the range of [0.0, 1.0)
* Use numpy.random.uniform to generate an n-dimensional array of random float numbers in the range of [low, high)

In [52]:
import numpy
numpy.random.rand(2, 2)

array([[0.8107692 , 0.98447939],
       [0.43385124, 0.61605599]])

In [53]:
random_float_array = numpy.random.uniform(25.5, 99.5, size=(3, 2))
random_float_array

array([[92.92279228, 49.44112099],
       [88.11105053, 63.04792379],
       [37.68648836, 70.05265552]])

## Generate a random n-dimensional array of Integers numbers : 
* numpy.random.randint()to generate a random n-dimensional array of integers.

In [54]:
random_integer = numpy.random.randint(1, 10, 5)
random_integer
# Here in the parameters:
## First and the second are used for generating the 

array([4, 3, 4, 1, 2])

## Generating the two dimentional array(matrix out of the numbers):

In [55]:
numpy.random.randint(1, 10,  size = (2,2))

array([[2, 3],
       [8, 6]])

## Choose the random element from the array of numbers or sequence

In [59]:
array =[10, 20, 30, 40, 50, 20, 40]
single_random_choice = numpy.random.choice(array, size=1)
print("single random choice from 1-D array", single_random_choice)

single random choice from 1-D array [10]


In [60]:
multiple_random_choice = numpy.random.choice(array, size=3, replace=False)
print("multiple random choice from 1-D array without replacement ", multiple_random_choice)

multiple random choice from 1-D array without replacement  [40 20 50]


In [61]:
multiple_random_choice = numpy.random.choice(array, size=3, replace=True)
print("multiple random choice from 1-D array with replacement ", multiple_random_choice)

multiple random choice from 1-D array with replacement  [30 10 40]
